/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.smc.liferay.feedback.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Manager service. Represents a row in the &quot;feedback_Manager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.smc.liferay.feedback.model.impl.ManagerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.smc.liferay.feedback.model.impl.ManagerImpl}.
 * </p>
 *
 * @author dbg
 * @see Manager
 * @see it.smc.liferay.feedback.model.impl.ManagerImpl
 * @see it.smc.liferay.feedback.model.impl.ManagerModelImpl
 * @generated
 */
public interface ManagerModel extends BaseModel<Manager>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a manager model instance should use the {@link Manager} interface instead.
	 */

	/**
	 * Returns the primary key of this manager.
	 *
	 * @return the primary key of this manager
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this manager.
	 *
	 * @param primaryKey the primary key of this manager
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the manager ID of this manager.
	 *
	 * @return the manager ID of this manager
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this manager.
	 *
	 * @param managerId the manager ID of this manager
	 */
	public void setManagerId(long managerId);

	/**
	 * Returns the group ID of this manager.
	 *
	 * @return the group ID of this manager
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this manager.
	 *
	 * @param groupId the group ID of this manager
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this manager.
	 *
	 * @return the company ID of this manager
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this manager.
	 *
	 * @param companyId the company ID of this manager
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this manager.
	 *
	 * @return the user ID of this manager
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this manager.
	 *
	 * @param userId the user ID of this manager
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this manager.
	 *
	 * @return the user uuid of this manager
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this manager.
	 *
	 * @param userUuid the user uuid of this manager
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this manager.
	 *
	 * @return the user name of this manager
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this manager.
	 *
	 * @param userName the user name of this manager
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this manager.
	 *
	 * @return the create date of this manager
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this manager.
	 *
	 * @param createDate the create date of this manager
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this manager.
	 *
	 * @return the modified date of this manager
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this manager.
	 *
	 * @param modifiedDate the modified date of this manager
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plid of this manager.
	 *
	 * @return the plid of this manager
	 */
	public long getPlid();

	/**
	 * Sets the plid of this manager.
	 *
	 * @param plid the plid of this manager
	 */
	public void setPlid(long plid);

	/**
	 * Returns the description of this manager.
	 *
	 * @return the description of this manager
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this manager.
	 *
	 * @param description the description of this manager
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this manager.
	 *
	 * @return the url of this manager
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this manager.
	 *
	 * @param url the url of this manager
	 */
	public void setUrl(String url);

	/**
	 * Returns the user agent of this manager.
	 *
	 * @return the user agent of this manager
	 */
	@AutoEscape
	public String getUserAgent();

	/**
	 * Sets the user agent of this manager.
	 *
	 * @param userAgent the user agent of this manager
	 */
	public void setUserAgent(String userAgent);

	/**
	 * Returns the internal note of this manager.
	 *
	 * @return the internal note of this manager
	 */
	@AutoEscape
	public String getInternalNote();

	/**
	 * Sets the internal note of this manager.
	 *
	 * @param internalNote the internal note of this manager
	 */
	public void setInternalNote(String internalNote);

	/**
	 * Returns the file of this manager.
	 *
	 * @return the file of this manager
	 */
	@AutoEscape
	public String getFile();

	/**
	 * Sets the file of this manager.
	 *
	 * @param file the file of this manager
	 */
	public void setFile(String file);

	/**
	 * Returns the user manager ID of this manager.
	 *
	 * @return the user manager ID of this manager
	 */
	public long getUserManagerId();

	/**
	 * Sets the user manager ID of this manager.
	 *
	 * @param userManagerId the user manager ID of this manager
	 */
	public void setUserManagerId(long userManagerId);

	/**
	 * Returns the status of this manager.
	 *
	 * @return the status of this manager
	 */
	public int getStatus();

	/**
	 * Sets the status of this manager.
	 *
	 * @param status the status of this manager
	 */
	public void setStatus(int status);

	/**
	 * Returns the status date of this manager.
	 *
	 * @return the status date of this manager
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this manager.
	 *
	 * @param statusDate the status date of this manager
	 */
	public void setStatusDate(Date statusDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Manager manager);

	public int hashCode();

	public CacheModel<Manager> toCacheModel();

	public Manager toEscapedModel();

	public String toString();

	public String toXmlString();
}